### ISSUE TITLE
Could not resolve constructor for HandshakeMessage

### ISSUE THREAD

**Issue by abraaocaldas** [CodeBrig/Beam#3]
Hello,
I'm trying to run the  example of udp hole punching, when I try to start the UDPHoleClient I get the exception:

Could not resolve constructor for class com.codebrig.beam.system.messages.HandshakeMessage

On Android Studio with Java JDK 1.8.

**Comment by BFergerson** [comment]
@abraaocaldas, hello again. Do you think you could share the whole stack trace? I'm not sure what I could figure out from just that error message alone.

This is an ancient project. I mean it's built with NetBeans and Ant lol. If there is code or understanding you can extract from this library that would probably be much better than trying to rely on this library. I spent a lot of time getting UDP and UPnP hole punching working so it should work but again this is an old library. Likely someone else already doing those things better.

**Comment by abraaocaldas** [comment]
`W/System.err:     at io.protostuff.runtime.RuntimeEnv.newInstantiator(RuntimeEnv.java:252)
        at io.protostuff.runtime.RuntimeSchema.createFrom(RuntimeSchema.java:264)
W/System.err:     at io.protostuff.runtime.RuntimeSchema.createFrom(RuntimeSchema.java:172)
W/System.err:     at io.protostuff.runtime.IdStrategy.newSchema(IdStrategy.java:123)
W/System.err:     at io.protostuff.runtime.DefaultIdStrategy$Lazy.getSchema(DefaultIdStrategy.java:687)
W/System.err:     at io.protostuff.runtime.RuntimeSchema.getSchema(RuntimeSchema.java:134)
        at io.protostuff.runtime.RuntimeSchema.getSchema(RuntimeSchema.java:125)
W/System.err:     at com.codebrig.beam.messages.BeamMessage.getData(BeamMessage.java:302)
W/System.err:     at com.codebrig.beam.Communicator.send0(Communicator.java:590)
        at com.codebrig.beam.Communicator.queue(Communicator.java:801)
W/System.err:     at com.codebrig.beam.Communicator.performBeamHandshake(Communicator.java:245)
W/System.err:     at com.codebrig.beam.BeamClient.connect(BeamClient.java:216)
        at com.codebrig.beam.BeamClient.connect(BeamClient.java:147)
W/System.err:     at com.codebrig.beam.connection.traversal.punch.udp.client.UDPHoleClient.createHoleCommunicator(UDPHoleClient.java:89)
W/System.err:     at com.codebrig.beam.connection.traversal.punch.udp.client.UDPHoleClient.createHoleCommunicator(UDPHoleClient.java:72)`

Hey, your library is very good , there is some bugs with SSL, but in general is very nice, in fact I'm testing a lot of libraries but none of them work with restricted port NAT :| .
I'm having issues with one mobile carrier too that have a "custom NAT" that even some network tools have trouble detecting the NAT type.

If you have any suggestion I will gladly accept :)
